before:
  hooks:
    - task buf:generate

release:
  replace_existing_artifacts: true
  make_latest: true
  mode: replace

changelog:
  use: github
  filters:
    include:
      - "^feat"
      - "^fix"
      - "^chore"

builds:
  - env: ["CGO_ENABLED=0"]
    binary: envoy-oidc-authserver
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

kos:
  - repository: ghcr.io/shelmangroup/envoy-oidc-authserver
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    platforms:
      - linux/amd64
      - linux/arm64
