---
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis
spec:
  sentinel:
    replicas: 3
    exporter:
      enabled: false
      image: leominov/redis_sentinel_exporter:1.3.0
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: sentinel
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    customConfig:
      - "down-after-milliseconds 500"
      - "failover-timeout 2000"
  redis:
    replicas: 3
    exporter:
      enabled: false
      image: oliver006/redis_exporter:v1.24.0-alpine
    topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/component: redis
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
